/** Настройки успешно получены */
export const FETCH_CONFIG_START = 'FETCH_CONFIG_START';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILED = 'FETCH_CONFIG_FAILED';

/** Выбор получателя */
export const CHANGE_RECIPIENT = 'CHANGE_RECIPIENT';

/** Изменить текст фильтра списка чатов */
export const CHANGE_CHAT_FILTER = 'CHANGE_CHAT_FILTER';

/** Изменить дополнительную информацию о получателе */
export const CHANGE_RECIPIENT_CHAT_INFO = 'CHANGE_RECIPIENT_CHAT_INFO';

/** Запрос списка пользователей и чатов */
export const FETCH_CHATS_START = 'FETCH_CHATS_START';
/** Список пользователей и чатов успешно получен */
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
/** Ошибка получения списка пользователей и чатов */
export const FETCH_CHATS_FAILED = 'FETCH_CHATS_FAILED';

/** Количество непрочитанных сообщений успешно получено */
export const FETCH_UNREAD_SUCCESS = 'FETCH_UNREAD_SUCCESS';

/** Запрос списка пользователей и чатов */
export const FETCH_ONLINE_SUCCESS = 'FETCH_ONLINE_SUCCESS';

/** Запрос списка сообщений */
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
/** Список сообщений успешно получен */
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
/** Ошибка получения списка сообщений */
export const FETCH_MESSAGES_FAILED = 'FETCH_MESSAGES_FAILED';

/** Запрос истории сообщений */
export const FETCH_HISTORY_MESSAGES_START = 'FETCH_HISTORY_MESSAGES_START';
/** История сообщений успешно получена */
export const FETCH_HISTORY_MESSAGES_SUCCESS = 'FETCH_HISTORY_MESSAGES_SUCCESS';
/** Ошибка получения истории сообщений */
export const FETCH_HISTORY_MESSAGES_FAILED = 'FETCH_HISTORY_MESSAGES_FAILED';

/** Запрос отправки сообщения */
export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
/** Сообщение успешно отправлено */
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
/** Ошибка отправки сообщения */
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

/** Метка прочтения сообщений успешно сохранена */
export const READ_MESSAGE_SUCCESS = 'READ_MESSAGE_SUCCESS';

/** Запрос списка новых сообщений */
export const FETCH_NEW_MESSAGES_SUCCESS = 'FETCH_NEW_MESSAGES_SUCCESS';

/** Изменить текст сообщения */
export const CHANGE_MESSAGE_TEXT = 'CHANGE_MESSAGE_TEXT';

/** Очистить список сообщений */
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

/** Установить префикс сообщения */
export const PREFIX_MESSAGE_TEXT = 'PREFIX_MESSAGE_TEXT';

/** Сбрасить флаг необходимости скролла сообщений */
export const SCROLL_TO_BOTTOM_DISABLE = 'SCROLL_TO_BOTTOM_DISABLE';

/** Включение режима "Шпион" */
export const SPY_MODE_ON = 'SPY_MODE_ON';

/** Выключение режима "Шпион" */
export const SPY_MODE_OFF = 'SPY_MODE_OFF';

/** Выбор отправителя в режиме "Шпион" */
export const SPY_CHANGE_SENDER = 'SPY_CHANGE_SENDER';

/** Выбор получателя в режиме "Шпион" */
export const SPY_CHANGE_RECIPIENT = 'SPY_CHANGE_RECIPIENT';

/** Флаг отображения чата */
export const CHAT_SHOW = 'CHAT_SHOW';

/** Флаг скрытия чата */
export const CHAT_HIDE = 'CHAT_HIDE';

export const SETTING_CHANGE_REPORT_EMAIL = 'SETTING_CHANGE_REPORT_EMAIL';
export const SETTING_SAVE_REPORT_EMAIL = 'SETTING_SAVE_REPORT_EMAIL';

/*
    Список активных пользователей
 */
export const FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILED = 'FETCH_EMPLOYEES_FAILED';

/*
    Анкета для клиентов
 */
export const FETCH_CUSTOMER_QUESTION_START = 'FETCH_CUSTOMER_QUESTION_START';
export const FETCH_CUSTOMER_QUESTION_SUCCESS = 'FETCH_CUSTOMER_QUESTION_SUCCESS';
export const FETCH_CUSTOMER_QUESTION_FAILED = 'FETCH_CUSTOMER_QUESTION_FAILED';

export const SAVE_CUSTOMER_QUESTION_START = 'SAVE_CUSTOMER_QUESTION_START';
export const SAVE_CUSTOMER_QUESTION_SUCCESS = 'SAVE_CUSTOMER_QUESTION_SUCCESS';
export const SAVE_CUSTOMER_QUESTION_FAILED = 'SAVE_CUSTOMER_QUESTION_FAILED';

export const FETCH_SETTING_CUSTOMER_PROFILE_START = 'FETCH_SETTING_CUSTOMER_PROFILE_START';
export const FETCH_SETTING_CUSTOMER_PROFILE_SUCCESS = 'FETCH_SETTING_CUSTOMER_PROFILE_SUCCESS';
export const FETCH_SETTING_CUSTOMER_PROFILE_FAILED = 'FETCH_SETTING_CUSTOMER_PROFILE_FAILED';

export const APPEND_SETTING_CUSTOMER_PROFILE_START = 'APPEND_SETTING_CUSTOMER_PROFILE_START';
export const APPEND_SETTING_CUSTOMER_PROFILE_SUCCESS = 'APPEND_SETTING_CUSTOMER_PROFILE_SUCCESS';
export const APPEND_SETTING_CUSTOMER_PROFILE_FAILED = 'APPEND_SETTING_CUSTOMER_PROFILE_FAILED';

export const EDIT_SETTING_CUSTOMER_PROFILE_START = 'EDIT_SETTING_CUSTOMER_PROFILE_START';
export const EDIT_SETTING_CUSTOMER_PROFILE_SUCCESS = 'EDIT_SETTING_CUSTOMER_PROFILE_SUCCESS';
export const EDIT_SETTING_CUSTOMER_PROFILE_FAILED = 'EDIT_SETTING_CUSTOMER_PROFILE_FAILED';

export const REMOVE_SETTING_CUSTOMER_PROFILE_START = 'REMOVE_SETTING_CUSTOMER_PROFILE_START';
export const REMOVE_SETTING_CUSTOMER_PROFILE_SUCCESS = 'REMOVE_SETTING_CUSTOMER_PROFILE_SUCCESS';
export const REMOVE_SETTING_CUSTOMER_PROFILE_FAILED = 'REMOVE_SETTING_CUSTOMER_PROFILE_FAILED';

export const PANEL_CHAT_OPEN = 'PANEL_CHAT_OPEN';
export const PANEL_CHAT_CLOSE = 'PANEL_CHAT_CLOSE';
export const PANEL_CHAT_SELECTED = 'PANEL_CHAT_SELECTED';

export const FETCH_CHAT_USERS_START = 'FETCH_CHAT_USERS_START';
export const FETCH_CHAT_USERS_SUCCESS = 'FETCH_CHAT_USERS_SUCCESS';
export const FETCH_CHAT_USERS_FAILED = 'FETCH_CHAT_USERS_FAILED';

export const SAVE_CHAT_START = 'SAVE_CHAT_START';
export const SAVE_CHAT_SUCCESS = 'SAVE_CHAT_SUCCESS';
export const SAVE_CHAT_FAILED = 'SAVE_CHAT_FAILED';

export const SAVE_AVATAR_CHAT_START = 'SAVE_AVATAR_CHAT_START';
export const SAVE_AVATAR_CHAT_SUCCESS = 'SAVE_AVATAR_CHAT_SUCCESS';
export const SAVE_AVATAR_CHAT_FAILED = 'SAVE_AVATAR_CHAT_FAILED';

export const REMOVE_CHAT_START = 'REMOVE_CHAT_START';
export const REMOVE_CHAT_SUCCESS = 'REMOVE_CHAT_SUCCESS';
export const REMOVE_CHAT_FAILED = 'REMOVE_CHAT_FAILED';

export const FETCH_CUSTOMER_HISTORY_START = 'FETCH_CUSTOMER_HISTORY_START';
export const FETCH_CUSTOMER_HISTORY_SUCCESS = 'FETCH_CUSTOMER_HISTORY_SUCCESS';
export const FETCH_CUSTOMER_HISTORY_FAILED = 'FETCH_CUSTOMER_HISTORY_FAILED';

export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAILED = 'FETCH_CUSTOMERS_FAILED';

export const FETCH_CUSTOMERS_META_START = 'FETCH_CUSTOMERS_META_START';
export const FETCH_CUSTOMERS_META_SUCCESS = 'FETCH_CUSTOMERS_META_SUCCESS';
export const FETCH_CUSTOMERS_META_FAILED = 'FETCH_CUSTOMERS_META_FAILED';

export const CHANGE_CUSTOMER_PAGE = 'CHANGE_CUSTOMER_PAGE';

export const CHANGE_CUSTOMER_FILTER_ID = 'CHANGE_CUSTOMER_FILTER_ID';
export const CHANGE_CUSTOMER_FILTER_FI = 'CHANGE_CUSTOMER_FILTER_FI';
export const CHANGE_CUSTOMER_FILTER_CITY = 'CHANGE_CUSTOMER_FILTER_CITY';
export const CHANGE_CUSTOMER_FILTER_STATUS = 'CHANGE_CUSTOMER_FILTER_STATUS';
export const CHANGE_CUSTOMER_FILTER_AGE_MIN = 'CHANGE_CUSTOMER_FILTER_AGE_MIN';
export const CHANGE_CUSTOMER_FILTER_AGE_MAX = 'CHANGE_CUSTOMER_FILTER_AGE_MAX';

export const CHANGE_TASK_MODE = 'CHANGE_TASK_MODE';
export const CHANGE_TASK_FILTER_WHOM_TASK = 'CHANGE_TASK_FILTER_WHOM_TASK';
export const CHANGE_TASK_FILTER_BY_WHOM_TASK = 'CHANGE_TASK_FILTER_BY_WHOM_TASK';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';

export const CHANGE_TASK_CARD_MODE = 'CHANGE_TASK_CARD_MODE';
export const CHANGE_TASK_CARD_NAME = 'CHANGE_TASK_CARD_NAME';
export const CHANGE_TASK_CARD_EDIT_TEXT = 'CHANGE_TASK_CARD_EDIT_TEXT';
export const CHANGE_TASK_CARD_CONFIRMATION = 'CHANGE_TASK_CARD_CONFIRMATION';

export const TASK_CARD_CREATE = 'TASK_CARD_CREATE';
export const TASK_CARD_SHOW = 'TASK_CARD_SHOW';
export const TASK_CARD_HIDE = 'TASK_CARD_HIDE';

export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED';

export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

export const REMOVE_TASK_START = 'REMOVE_TASK_START';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';
export const REMOVE_TASK_FAILED = 'REMOVE_TASK_FAILED';

export const FETCH_TASK_COMMENTS_START = 'FETCH_TASK_COMMENTS_START';
export const FETCH_TASK_COMMENTS_SUCCESS = 'FETCH_TASK_COMMENTS_SUCCESS';
export const FETCH_TASK_COMMENTS_FAILED = 'FETCH_TASK_COMMENTS_FAILED';

export const FETCH_TASK_SITES_START = 'FETCH_TASK_SITES_START';
export const FETCH_TASK_SITES_SUCCESS = 'FETCH_TASK_SITES_SUCCESS';
export const FETCH_TASK_SITES_FAILED = 'FETCH_TASK_SITES_FAILED';

export const APPEND_TASK_COMMENTS_START = 'APPEND_TASK_COMMENTS_START';
export const APPEND_TASK_COMMENTS_SUCCESS = 'APPEND_TASK_COMMENTS_SUCCESS';
export const APPEND_TASK_COMMENTS_FAILED = 'APPEND_TASK_COMMENTS_FAILED';

export const FETCH_SCHEDULES_START = 'FETCH_SCHEDULES_START';
export const FETCH_SCHEDULES_SUCCESS = 'FETCH_SCHEDULES_SUCCESS';
export const FETCH_SCHEDULES_FAILED = 'FETCH_SCHEDULES_FAILED';

export const UPDATE_SCHEDULE_START = 'UPDATE_SCHEDULE_START';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_FAILED = 'UPDATE_SCHEDULE_FAILED';